"""
Strategy data structures — market snapshots and trading signals.

These are plain dataclasses (not Pydantic) because they are internal
objects created at very high frequency (every tick).  Avoiding Pydantic
validation overhead keeps the hot path lean.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal


@dataclass(slots=True)
class MarketSnapshot:
    """Point-in-time view of a single instrument.

    Built from the rolling quote buffer every time the strategy engine
    evaluates a symbol.

    Attributes:
        symbol: Contract symbol (e.g. ``"MBT"``, ``"MET"``).
        bid: Best bid price.
        ask: Best ask price.
        last: Last traded price.
        spread: ``ask - bid`` in price units.
        volume: Cumulative session volume from the latest quote.
        timestamp: Unix epoch seconds of the most recent tick.
        last_n_ticks: Most recent *N* trade prices (oldest first).
        micro_price: Bid/ask midpoint, or ``None`` when the spread is
            crossed or unavailable.
        spread_bps: Spread expressed in basis points relative to the
            micro-price (or last price if micro-price is ``None``).
    """

    symbol: str
    bid: float
    ask: float
    last: float
    spread: float
    volume: int
    timestamp: float
    last_n_ticks: list[float] = field(default_factory=list)
    micro_price: float | None = None
    spread_bps: float | None = None

    def __post_init__(self) -> None:
        """Derive micro-price and spread_bps if not supplied."""
        if self.micro_price is None:
            self.micro_price = (self.bid + self.ask) / 2.0
        if self.spread_bps is None:
            ref_price = self.micro_price if self.micro_price > 0 else self.last
            if ref_price > 0:
                self.spread_bps = (self.spread / ref_price) * 10_000.0
            else:
                self.spread_bps = 0.0


@dataclass(slots=True)
class Signal:
    """A tradeable signal generated by the strategy engine.

    Signals are *actionable but advisory* — the orchestrator must still
    run them through the risk engine before submitting orders.

    Attributes:
        symbol: Contract symbol.
        direction: ``"long"``, ``"short"``, or ``"flat"`` (flat = no trade).
        confidence: 0.0–1.0 score reflecting how strongly the strategy
            believes this signal will be profitable.
        entry_price: Limit price for entry, or ``None`` for market order.
        stop_price: Hard stop-loss price (always set when direction is
            not flat).
        target_price: Take-profit price.
        rationale: Human-readable explanation of why this signal fired.
        timestamp: Unix epoch seconds when the signal was generated.
    """

    symbol: str
    direction: Literal["long", "short", "flat"]
    confidence: float
    entry_price: float | None
    stop_price: float
    target_price: float
    rationale: str
    timestamp: float
