"""
Pydantic v2 models for the Tradovate trading bot.

All models use strict field types, validation, and descriptive docstrings
to ensure correctness when parsing API responses and constructing requests.
"""

from __future__ import annotations

from typing import Literal, Optional

from pydantic import BaseModel, Field


class OrderRequest(BaseModel):
    """Request payload for placing a single order via the Tradovate API.

    Attributes:
        account_spec: Account specifier string (e.g., username or account name).
        account_id: Numeric account identifier on Tradovate.
        action: Trade direction — Buy or Sell.
        symbol: Contract symbol (e.g., "MESM5", "MNQM5").
        order_qty: Number of contracts.
        order_type: Order type — Market, Limit, Stop, StopLimit, or MIT.
        price: Limit price; required for Limit and StopLimit orders.
        stop_price: Stop trigger price; required for Stop and StopLimit orders.
        time_in_force: Time-in-force dictionary; defaults to {"tif": "Day"}.
        is_automated: Whether this order was generated by an automated system.
    """

    account_spec: str
    account_id: int
    action: Literal["Buy", "Sell"]
    symbol: str
    order_qty: int = Field(gt=0, description="Must be a positive integer")
    order_type: Literal["Market", "Limit", "Stop", "StopLimit", "MIT"]
    price: Optional[float] = None
    stop_price: Optional[float] = None
    time_in_force: Optional[dict] = Field(
        default_factory=lambda: {"tif": "Day"}
    )
    is_automated: bool = True


class BracketConfig(BaseModel):
    """Profit-target and stop-loss configuration for a bracket (OCO) order.

    Attributes:
        profit_target: Price offset (in ticks or absolute) for the take-profit leg.
        stop_loss: Price offset (in ticks or absolute) for the stop-loss leg.
    """

    profit_target: float = Field(gt=0, description="Must be a positive value")
    stop_loss: float = Field(gt=0, description="Must be a positive value")


class BracketOrderRequest(OrderRequest):
    """Order request with an attached bracket (OCO) configuration.

    The parent OrderRequest fields are inherited.  The ``order_type`` is
    intentionally omitted from the bracket request because the entry leg is
    always submitted as a Market or Limit order, with TP/SL legs attached
    automatically by the Tradovate bracket-order endpoint.
    """

    bracket: BracketConfig


class Order(BaseModel):
    """Represents a single order as returned by the Tradovate API.

    Attributes:
        id: Unique order identifier assigned by Tradovate.
        account_id: Numeric account identifier.
        symbol: Contract symbol.
        action: Buy or Sell.
        order_qty: Requested contract quantity.
        order_type: Market, Limit, Stop, StopLimit, or MIT.
        order_status: Current lifecycle status (e.g., Working, Filled, Cancelled, Rejected).
        price: Limit price (if applicable).
        stop_price: Stop trigger price (if applicable).
        filled_qty: Quantity that has been filled so far.
        avg_fill_price: Volume-weighted average fill price.
    """

    id: int
    account_id: int
    symbol: str
    action: Literal["Buy", "Sell"]
    order_qty: int
    order_type: Literal["Market", "Limit", "Stop", "StopLimit", "MIT"]
    order_status: str
    price: Optional[float] = None
    stop_price: Optional[float] = None
    filled_qty: int = 0
    avg_fill_price: Optional[float] = None


class Position(BaseModel):
    """Current position snapshot for a single contract.

    Attributes:
        id: Unique position identifier.
        account_id: Numeric account identifier.
        symbol: Contract symbol.
        net_pos: Net position size (positive = long, negative = short, zero = flat).
        avg_price: Average entry price for the position.
        open_pnl: Unrealized profit/loss at current mark.
        realized_pnl: Realized profit/loss for closed portions today.
        total_pnl: Combined open + realized PnL.
    """

    id: int
    account_id: int
    symbol: str
    net_pos: int
    avg_price: float
    open_pnl: float = 0.0
    realized_pnl: float = 0.0
    total_pnl: float = 0.0


class Account(BaseModel):
    """Tradovate account summary.

    Attributes:
        id: Unique account identifier.
        name: Human-readable account name.
        net_liq: Net liquidation value (cash + open PnL).
        realized_pnl: Realized profit/loss for the current session.
        open_pnl: Unrealized profit/loss across all positions.
        balance: Total account balance.
        available_funds: Funds available for new positions.
    """

    id: int
    name: str
    net_liq: float
    realized_pnl: float = 0.0
    open_pnl: float = 0.0
    balance: float
    available_funds: float


class Quote(BaseModel):
    """Real-time market data quote for a single contract.

    Attributes:
        symbol: Contract symbol.
        bid: Best bid price.
        ask: Best ask price.
        last: Last traded price.
        volume: Cumulative session volume.
        timestamp: ISO-8601 timestamp of the quote.
    """

    symbol: str
    bid: float
    ask: float
    last: float
    volume: int = 0
    timestamp: str


class Contract(BaseModel):
    """Tradovate contract metadata.

    Attributes:
        id: Unique contract identifier.
        name: Tradovate contract name (e.g., "MESU5").
        contract_maturity: Expiration / maturity date or code.
        product_type: Futures, Options, etc.
        tick_size: Minimum price increment.
        tick_value: Monetary value of one tick.
        point_value: Monetary value of a full point move.
        multiplier: Contract multiplier (e.g., 50 for MES, 20 for MNQ).
    """

    id: int
    name: str
    contract_maturity: str
    product_type: str
    tick_size: float
    tick_value: float
    point_value: float
    multiplier: float


class OrderResponse(BaseModel):
    """Synchronous response after placing a single order.

    Attributes:
        order_id: Tradovate-assigned order identifier (0 if the order was rejected).
        status: Human-readable status string (e.g., "Ok", "Rejected").
        message: Optional detail message, typically populated on rejection.
    """

    order_id: int
    status: str
    message: Optional[str] = None


class BracketOrderResponse(BaseModel):
    """Synchronous response after placing a bracket (OCO) order.

    Attributes:
        entry_order_id: Tradovate-assigned ID for the entry leg.
        profit_target_order_id: Tradovate-assigned ID for the take-profit leg.
        stop_loss_order_id: Tradovate-assigned ID for the stop-loss leg.
        status: Human-readable status string (e.g., "Ok", "Rejected").
    """

    entry_order_id: int
    profit_target_order_id: int
    stop_loss_order_id: int
    status: str
